version: '3.7'
services:
  db:
    restart: always
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql
  app:
    build:
      context: .
      dockerfile: ./docker_dev/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid &&
                      bin/rails s -p 4000 -b '0.0.0.0'"
    volumes:
      - .:/teamdev_challenges
      - "bundle:/usr/local/bundle"
    ports:
      - "4000:4000"
    depends_on:
      - db
      - chrome
  chrome:
    image: selenium/standalone-chrome:3.141.59-dubnium
    ports:
      - 4444:4444

volumes:
  bundle:
    driver: local
  postgresql-data:
    driver: local
