default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USERNAME", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>
  host: <%= ENV.fetch("POSTGRESQL_HOST", "db") %>

development:
  <<: *default
  database: teamdev_challenges_development

test:
  <<: *default
  database: teamdev_challenges_test

production:
  <<: *default
  database: teamdev_challenges_production